spring:
  application:
    name: xeine

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: ${PORT:8080}

jwt:
  secret: ${JWT_SECRET}
  access:
    expiration: ${JWT_ACCESS_EXPIRATION}
  refresh:
    expiration: ${JWT_REFRESH_EXPIRATION}

cookie:
  access:
    name: ${COOKIE_ACCESS_NAME:access_token}
  refresh:
    name: ${COOKIE_REFRESH_NAME:refresh_token}

logging:
  level:
    org:
      springframework:
        security: DEBUG

twilio:
  account_sid: ${TWILIO_ACCOUNT_SID}
  auth_token: ${TWILIO_AUTH_TOKEN}
  phone_number: ${TWILIO_PHONE_NUMBER}

# Local Storage Configuration (fallback)
app:
  upload:
    dir: ${APP_UPLOAD_DIR:./upload}
  base:
    url: ${BASE_URL:http://localhost:8080}
